"""create production game schema

Revision ID: 1c8d33f92ba8
Revises:
Create Date: 2026-08-21 02:08:05.882345
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1c8d33f92ba8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("code", sa.String(length=5), nullable=False),
        sa.Column("game_id", sa.String(length=32), nullable=False),
        sa.Column("host_player_id", sa.String(length=64), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_rooms_expired_at"), "rooms", ["expired_at"], unique=False)
    op.create_index(op.f("ix_rooms_expires_at"), "rooms", ["expires_at"], unique=False)
    op.create_index(op.f("ix_rooms_game_id"), "rooms", ["game_id"], unique=False)
    op.create_index(op.f("ix_rooms_phase"), "rooms", ["phase"], unique=False)
    op.create_table(
        "game_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_code", sa.String(length=5), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_code", "sequence_number", name="uq_event_room_sequence"),
    )
    op.create_index(op.f("ix_game_events_event_type"), "game_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_game_events_room_code"), "game_events", ["room_code"], unique=False)
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_code", sa.String(length=5), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_sessions_room_code"), "game_sessions", ["room_code"], unique=True)
    op.create_table(
        "game_state_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_code", sa.String(length=5), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_code", "version", name="uq_snapshot_room_version"),
    )
    op.create_index(op.f("ix_game_state_snapshots_room_code"), "game_state_snapshots", ["room_code"], unique=False)
    op.create_table(
        "players",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("room_code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=24), nullable=False),
        sa.Column("normalized_name", sa.String(length=24), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_code", "normalized_name", name="uq_player_room_name"),
    )
    op.create_index(op.f("ix_players_room_code"), "players", ["room_code"], unique=False)
    op.create_index(op.f("ix_players_token_expires_at"), "players", ["token_expires_at"], unique=False)
    op.create_index(op.f("ix_players_token_hash"), "players", ["token_hash"], unique=True)
    op.create_table(
        "results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_code", sa.String(length=5), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_code", "round_number", name="uq_result_room_round"),
    )
    op.create_index(op.f("ix_results_room_code"), "results", ["room_code"], unique=False)
    op.create_table(
        "rounds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_code", sa.String(length=5), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("prompt", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_code", "number", name="uq_round_room_number"),
    )
    op.create_index(op.f("ix_rounds_room_code"), "rounds", ["room_code"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_code", sa.String(length=5), nullable=False),
        sa.Column("player_id", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "operation", "key", name="uq_idempotency_operation"),
    )
    op.create_index(op.f("ix_idempotency_records_player_id"), "idempotency_records", ["player_id"], unique=False)
    op.create_index(op.f("ix_idempotency_records_room_code"), "idempotency_records", ["room_code"], unique=False)
    op.create_table(
        "player_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_code", sa.String(length=5), nullable=False),
        sa.Column("player_id", sa.String(length=64), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "operation", "idempotency_key", name="uq_action_idempotency"),
    )
    op.create_index("ix_action_room_round", "player_actions", ["room_code", "round_number"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_action_room_round", table_name="player_actions")
    op.drop_table("player_actions")
    op.drop_index(op.f("ix_idempotency_records_room_code"), table_name="idempotency_records")
    op.drop_index(op.f("ix_idempotency_records_player_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_rounds_room_code"), table_name="rounds")
    op.drop_table("rounds")
    op.drop_index(op.f("ix_results_room_code"), table_name="results")
    op.drop_table("results")
    op.drop_index(op.f("ix_players_token_hash"), table_name="players")
    op.drop_index(op.f("ix_players_token_expires_at"), table_name="players")
    op.drop_index(op.f("ix_players_room_code"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_game_state_snapshots_room_code"), table_name="game_state_snapshots")
    op.drop_table("game_state_snapshots")
    op.drop_index(op.f("ix_game_sessions_room_code"), table_name="game_sessions")
    op.drop_table("game_sessions")
    op.drop_index(op.f("ix_game_events_room_code"), table_name="game_events")
    op.drop_index(op.f("ix_game_events_event_type"), table_name="game_events")
    op.drop_table("game_events")
    op.drop_index(op.f("ix_rooms_phase"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_game_id"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_expires_at"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_expired_at"), table_name="rooms")
    op.drop_table("rooms")
    # ### end Alembic commands ###
