"""Application service contract consumed by HTTP and WebSocket transports."""

from typing import Any, Protocol

from backend.config import GameId


class RoomApplication(Protocol):
    async def create_room(self, name: str, game_id: GameId) -> dict[str, str]: ...
    async def join_room(self, code: str, name: str) -> dict[str, str]: ...
    async def public_state(self, code: str, token: str) -> dict[str, Any]: ...
    async def start(self, code: str, token: str, key: str | None = None) -> dict[str, Any]: ...
    async def force_resolve(self, code: str, token: str, key: str | None = None) -> dict[str, Any]: ...
    async def next_round(self, code: str, token: str, key: str | None = None) -> dict[str, Any]: ...
    async def submit_action(
        self,
        code: str,
        token: str,
        values: dict[str, Any],
        key: str,
    ) -> dict[str, Any]: ...
    async def expire_idle_rooms(self) -> list[str]: ...
    async def active_room_count(self) -> int: ...
