"""Repository and coordination interfaces used by application services."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from contextlib import AbstractAsyncContextManager
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol

from backend.domain.events import EventType
from backend.models import Room


@dataclass(slots=True)
class IdempotencyResult:
    operation: str
    response: dict[str, Any]


class RoomTransaction(Protocol):
    room: Room
    player_id: str | None

    async def add_player_credential(self, player_id: str, token_hash: str, expires_at: datetime) -> None: ...
    async def find_idempotency(self, operation: str, key: str) -> IdempotencyResult | None: ...
    async def record_action(self, player_id: str, operation: str, key: str, values: dict[str, Any]) -> None: ...
    async def record_idempotency(self, player_id: str, operation: str, key: str, response: dict[str, Any]) -> None: ...
    async def add_event(self, event_type: EventType, payload: dict[str, Any]) -> None: ...


class RoomRepository(Protocol):
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...
    async def ready(self) -> bool: ...
    async def create(self, room: Room, token_hash: str, expires_at: datetime) -> None: ...
    async def load_authenticated(self, code: str, token_hash: str) -> tuple[Room, str]: ...
    def transaction(self, code: str, token_hash: str | None = None) -> AbstractAsyncContextManager[RoomTransaction]: ...
    async def expire_idle(self, now: datetime) -> list[str]: ...
    async def active_count(self) -> int: ...


class Cache(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl_seconds: int) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def ready(self) -> bool: ...
    async def close(self) -> None: ...


class EventPublisher(Protocol):
    async def publish(self, room_code: str, version: int) -> None: ...


EventHandler = Callable[[str, int], Awaitable[None]]


class EventBus(EventPublisher, Protocol):
    async def start(self, handler: EventHandler) -> None: ...
    async def ready(self) -> bool: ...
    async def close(self) -> None: ...


class RateLimiter(Protocol):
    async def check(self, scope: str, identity: str, limit: str) -> None: ...
    async def close(self) -> None: ...


class LockManager(Protocol):
    def hold(self, key: str) -> AbstractAsyncContextManager[None]: ...
    async def close(self) -> None: ...
